import {
  Apple,
  ArrowLeftRight,
  ArrowUp,
  BadgeDollarSign,
  Banknote,
  BanknoteArrowDown,
  BanknoteArrowUp,
  Bell,
  BookOpenText,
  Briefcase,
  Car,
  CarTaxiFront,
  Cat,
  ChartLine,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  ChevronUp,
  CircleAlert,
  CircleCheckBig,
  Clapperboard,
  Copy,
  CreditCard,
  Drill,
  Droplet,
  Ellipsis,
  Eye,
  EyeOff,
  Flame,
  Flower,
  Gamepad2,
  Gem,
  Globe,
  HandCoins,
  HandHeart,
  Heart,
  House,
  Info,
  Landmark,
  LayoutGrid,
  Loader,
  LoaderCircle,
  Lock,
  LogOut,
  Mail,
  Megaphone,
  MessageCircleMore,
  Moon,
  MousePointerClick,
  Percent,
  Plus,
  RectangleEllipsis,
  Scissors,
  Search,
  Settings,
  Shirt,
  Smartphone,
  SquarePen,
  Sun,
  Trash2,
  TriangleAlert,
  Trophy,
  Truck,
  Umbrella,
  User,
  UserRound,
  Utensils,
  Volleyball,
  Wallet,
  WashingMachine,
  X,
  Zap,
} from 'lucide-react';

export const icons = [
  { role: 'advertisement', name: 'megaphone', component: Megaphone },
  { role: 'appliance', name: 'washing-machine', component: WashingMachine },
  { role: 'arrow-up', name: 'arrow-up', component: ArrowUp },
  { role: 'banknote', name: 'banknote', component: Banknote },
  { role: 'books', name: 'book-open-text', component: BookOpenText },
  { role: 'cafe', name: 'utensils', component: Utensils },
  { role: 'car', name: 'car', component: Car },
  { role: 'card', name: 'credit-card', component: CreditCard },
  { role: 'chat', name: 'message-circle-more', component: MessageCircleMore },
  { role: 'check', name: 'check', component: Check },
  { role: 'chevron-down', name: 'chevron-down', component: ChevronDown },
  { role: 'chevron-left', name: 'chevron-left', component: ChevronLeft },
  { role: 'chevron-right', name: 'chevron-right', component: ChevronRight },
  { role: 'chevron-up', name: 'chevron-up', component: ChevronUp },
  { role: 'chevrons-left', name: 'chevrons-left', component: ChevronsLeft },
  { role: 'chevrons-right', name: 'chevrons-right', component: ChevronsRight },
  { role: 'close', name: 'x', component: X },
  { role: 'clothes', name: 'shirt', component: Shirt },
  { role: 'copy', name: 'copy', component: Copy },
  {
    role: 'currency-exchange',
    name: 'badge-dollar-sign',
    component: BadgeDollarSign,
  },
  { role: 'dark', name: 'moon', component: Moon },
  { role: 'dashboard', name: 'layout-grid', component: LayoutGrid },
  { role: 'delete', name: 'trash-2', component: Trash2 },
  { role: 'delivery', name: 'truck', component: Truck },
  { role: 'donations', name: 'hand-heart', component: HandHeart },
  { role: 'edit', name: 'square-pen', component: SquarePen },
  { role: 'electricity', name: 'zap', component: Zap },
  { role: 'email', name: 'mail', component: Mail },
  { role: 'entertainment', name: 'gamepad-2', component: Gamepad2 },
  { role: 'error', name: 'triangle-alert', component: TriangleAlert },
  { role: 'flowers', name: 'flower', component: Flower },
  { role: 'gas', name: 'flame', component: Flame },
  { role: 'groceries', name: 'apple', component: Apple },
  { role: 'healthcare', name: 'heart', component: Heart },
  { role: 'hide', name: 'eye-off', component: EyeOff },
  { role: 'income', name: 'banknote-arrow-up', component: BanknoteArrowUp },
  { role: 'info', name: 'info', component: Info },
  { role: 'insurance', name: 'umbrella', component: Umbrella },
  { role: 'internet', name: 'globe', component: Globe },
  { role: 'investments', name: 'chart-line', component: ChartLine },
  { role: 'jewelry', name: 'gem', component: Gem },
  { role: 'light', name: 'sun', component: Sun },
  { role: 'loader', name: 'loader', component: Loader },
  { role: 'loader-circle', name: 'loader-circle', component: LoaderCircle },
  { role: 'loan', name: 'banknote-arrow-down', component: BanknoteArrowDown },
  { role: 'log-out', name: 'log-out', component: LogOut },
  { role: 'message', name: 'bell', component: Bell },
  { role: 'mobile-phone', name: 'smartphone', component: Smartphone },
  { role: 'movies', name: 'clapperboard', component: Clapperboard },
  { role: 'name', name: 'user', component: User },
  { role: 'others', name: 'ellipsis', component: Ellipsis },
  { role: 'password', name: 'lock', component: Lock },
  { role: 'payment', name: 'hand-coins', component: HandCoins },
  { role: 'percent', name: 'percent', component: Percent },
  { role: 'personal-care', name: 'scissors', component: Scissors },
  { role: 'pet-care', name: 'cat', component: Cat },
  { role: 'plus', name: 'plus', component: Plus },
  { role: 'prize', name: 'trophy', component: Trophy },
  { role: 'repair', name: 'drill', component: Drill },
  { role: 'saving', name: 'wallet', component: Wallet },
  { role: 'search', name: 'search', component: Search },
  { role: 'select', name: 'mouse-pointer-click', component: MousePointerClick },
  { role: 'settings', name: 'settings', component: Settings },
  { role: 'show', name: 'eye', component: Eye },
  { role: 'sport', name: 'volleyball', component: Volleyball },
  { role: 'status', name: 'rectangle-ellipsis', component: RectangleEllipsis },
  { role: 'success', name: 'circle-check-big', component: CircleCheckBig },
  { role: 'taxes', name: 'landmark', component: Landmark },
  { role: 'taxi', name: 'car-taxi-front', component: CarTaxiFront },
  { role: 'transfer', name: 'arrow-left-right', component: ArrowLeftRight },
  { role: 'travel', name: 'briefcase', component: Briefcase },
  { role: 'user', name: 'user-round', component: UserRound },
  { role: 'utility', name: 'house', component: House },
  { role: 'warning', name: 'circle-alert', component: CircleAlert },
  { role: 'water', name: 'droplet', component: Droplet },
] as const;
